.TH CODERDOJO\-GAMES "1" "17 Feb 2015"

.SH "NAME"
project\-name \- Short description

.SH "SYNOPSIS"
.PP
\fBcoderdojo-games\fP

.SH "DESCRIPTION"
.PP
\fBCoderDojo Games\fR is a collection of Flash games.

.SH "BUGS"
.PP
Please report bugs to <https://github.com/CoderDojoSi/coderdojo-games/issues>

.SH "AUTHOR"
.PP
Written by CoderDojo Slovenia team.

