#!/bin/sh

# see: dh_installdeb(1)

set -e

#DEBHELPER#


case "$1" in
    configure)

        # TODO
        
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0